#!/bin/bash

mv ~/.config/nvim ~/.config/nvimbackup

git clone git@github.com:AstroNvim/AstroNvim.git ~/.config/nvim

mkdir -p ~/.config/nvim/lua/user
cp -r ./lua/user/* ~/.config/nvim/lua/user/

nvim +PackerSync

