#!/bin/bash

CONFIG_DIR=~/.config

# Delete all nvim backups that are older than a month
find $CONFIG_DIR -regex "$CONFIG_DIR/nvimbackup.*" -type d -mtime +30 -exec echo {} \; 
mv "$CONFIG_DIR/nvim" "$CONFIG_DIR/nvimbackup-$( echo $RANDOM )"

git clone --depth 1 git@github.com:AstroNvim/template.git ~/.config/nvim

rm -rf "$CONFIG_DIR/nvim/lua/plugins"
ln -s `pwd`/plugins "$CONFIG_DIR/nvim/lua"
